# ────────────────────────────────────────────────────────────
# Matte Black Theme for Alacritty
# By noiseRandom
# https://github.com/tahayvr
# ────────────────────────────────────────────────────────────

[window]
# window padding {px}
padding.x = 12
padding.y = 12

[font]
size = 12.0



[colors]
[colors.primary]
background = "#121212"
foreground = "#bebebe"
dim_foreground = "#8a8a8d"

[colors.cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.vi_mode_cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.selection]
text = "CellForeground"
background = "#333333" #charcoal

[colors.normal]
black = "#2c2c2c"
red = "#b91c1c"
green = "#8a8a8d"
yellow = "#b91c1c"
blue = "#e68e0d"
magenta = "#b94d4d"
cyan = "#8a8a8d"
white = "#bebebe"

[colors.bright]
black = "#8a8a8d"
red = "#b90a0a"
green = "#8a8a8d"
yellow = "#b90a0a"
blue = "#f59e0b"
magenta = "#b94d4d"
cyan = "#333333"
white = "#bebebe"

[colors.dim]
black = "#2c2c2c"
red = "#800a0a"
green = "#8a8a8d"
yellow = "#800a0a"
blue = "#b37308"
magenta = "#b94d4d"
cyan = "#333333"
white = "#bebebe"
